# playbook.yml
- hosts: group1
  become: true
  roles:
    - role: openldap
      vars:
        openldap_home: "/tmp/openldap"
        openldap_admin_password: "admin"

    - role: traefik
    - role: whoami
      vars:
        whoami_home: "/tmp/whoami_group1"

- hosts: group2
  roles:
    - role: whoami
      vars:
        whoami_home: "/tmp/whoami_group2"

- hosts: group3
  roles:
    - role: whoami
      vars:
        whoami_home: "/tmp/whoami_group3"
